allowBuilds:
  esbuild: true
  simple-git-hooks: true
  unrs-resolver: true

engineStrict: true

onlyBuiltDependencies:
  - esbuild
  - oxc-resolver
  - simple-git-hooks
  - unrs-resolver

packageManagerStrictVersion: true

savePrefix: ""
