allowBuilds:
  esbuild: true
  simple-git-hooks: set this to true or false
  unrs-resolver: true

engineStrict: true

onlyBuiltDependencies:
  - esbuild
  - oxc-resolver
  - unrs-resolver

overrides:
  "@deno/shim-deno": 0.19.2

packageManagerStrictVersion: true

savePrefix: ""
